<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <ProjectReference Include="../../src/BlazorFormBuilder.Components/BlazorFormBuilder.Components.csproj" />
    <ProjectReference Include="../../src/BlazorFormBuilder.Plugins.Standard/BlazorFormBuilder.Plugins.Standard.csproj" />
  </ItemGroup>
</Project>
